---
title: "510-Capstone-Code-ML"
author: "Rochelle Rafn"
date: "2022-07-26"
output: html_document
---

```{r, warning=FALSE, message=FALSE}

library(tidyverse)
library(tidytext)
library(ggplot2)
library(skimr)
library(devtools)
library(visdat)
library(dplyr)
library(caret)
library(naivebayes)
library(SnowballC)
  data(stop_words)

all_sample_trans <- read.csv('/Users/rochellerafn/RStudio Files/h-and-m-personalized-fashion-recommendations/all_sample_transactions')
```

```{r}
str(all_sample_trans)
```

```{r}
all_sample_trans <- all_sample_trans %>%
  filter(!is.na(t_dat))

colSums(is.na(all_sample_trans))
```

```{r}
items_per_tran <- all_sample_trans %>%
  group_by(customer_id, t_dat) %>%
  count(customer_id) %>%
  arrange(desc(n))

head(items_per_tran)
```


```{r}
all_sample_trans_count <- left_join(all_sample_trans, items_per_tran, by= c("customer_id", "t_dat"))

str(all_sample_trans_count)
```

```{r}
all_sample_trans_count <- rename(all_sample_trans_count, n_items = n)

head(all_sample_trans_count)
```

```{r}
all_sample_trans_count %>%
  filter(age <=60, n_items < 200) %>%
ggplot(aes(age, n_items))+
  geom_jitter()
```

```{r}
str(all_sample_trans_count)
```

```{r}
all_sample_trans_count <- all_sample_trans_count %>%
  mutate(item_10_plus = ifelse(n_items >= 10, 1, 0))

head(all_sample_trans_count)
```

```{r}
str(all_sample_trans_count)
```

```{r}
library(moderndive)

more_than_10 <- lm(age ~ item_10_plus, data = all_sample_trans_count)

get_regression_table(more_than_10)
get_regression_summaries(more_than_10)
```

# Ideas for features... closelyfitting strappy straps crop
# word men for mature audience


```{r}
all_sample_trans_features <- all_sample_trans_count %>%
  mutate(t_dat = as.Date(t_dat)) %>%
  mutate(strappy = as.integer(str_detect(words,"[Ss]trappy | strap"))) %>% 
  mutate(cropped = as.integer(str_detect(words,"[Cc]ropped | crop"))) %>%
  mutate(fitted = as.integer(str_detect(words,"[Ff]itted"))) %>%
  mutate(front_print = as.integer(str_detect(words,"[Ff]ront | [Pp]rint"))) %>%
  mutate(mixed_solid_p = as.integer(str_detect(words,"[Mm]ixed | [Ss]olid | [Pp]rint"))) %>%
  mutate(placement_p = as.integer(str_detect(words,"[Pp]lacement | [Pp]rint"))) %>%
  mutate(underwear = as.integer(str_detect(words,"[Uu]nderwear"))) %>%
  mutate(bandeau = as.integer(str_detect(words,"[Bb]andeau"))) %>%
  mutate(men = as.integer(str_detect(words,"[Mm]en"))) %>%
  mutate(dusty = as.integer(str_detect(words,"[Dd]usty"))) %>%
  select(-words, -s_age, -X, -customer_id, -age_group, -t_dat, -postal_code, -article_id)

head(all_sample_trans_features)
```


```{r}
library(fastDummies)

all_sample_trans_features <- dummy_cols(all_sample_trans_features, select_columns = "club_member_status")

head(all_sample_trans_features)
```


```{r}
all_sample_trans_features <- all_sample_trans_features %>%
  select(-club_member_status)

head(all_sample_trans_features)
```



```{r}
n_items_lm <- lm(age ~ n_items, data = all_sample_trans_features) 

get_regression_table(n_items_lm)
get_regression_summaries(n_items_lm)
```


```{r}
strappy_crop_lm <- lm(age ~ strappy * cropped, data = all_sample_trans_features)

get_regression_table(strappy_crop_lm)
get_regression_summaries(strappy_crop_lm)
```


```{r}
front_print_lm <- lm(age ~ front_print * placement_p, data = all_sample_trans_features)

get_regression_table(front_print_lm)
get_regression_summaries(front_print_lm)
```


```{r}
sample_index <- createDataPartition(all_sample_trans_features$age, p = 0.8, list = FALSE)
sample_tr <- all_sample_trans_features[ sample_index, ]
sample_te <- all_sample_trans_features[-sample_index, ]


control <- trainControl(method="repeatedcv", number=5, repeats=3)

sample_m <- train(age ~ .,
                data = sample_tr, 
                method = "lm",
                trControl = control)

importance <- varImp(sample_m, scale=TRUE)
plot(importance)
```


```{r}
pr_all_sample_feature <- prcomp(x = select(all_sample_trans_features,-age), scale = T, center = T)
summary(pr_all_sample_feature)
```

```{r}
screeplot(pr_all_sample_feature, type = "lines")
```

```{r}
pr_all_sample_feature$rotation
```


```{r}
prc_sample_features <- bind_cols(select(all_sample_trans_features,age),as.data.frame(pr_all_sample_feature$x)) %>% 
  select(1:5) %>% 
  rename("Cheap-Active-Men" = PC1) %>% 
  rename("Multiple-Items" = PC2) %>% 
  rename("Commando" = PC3) %>% 
  rename("Front-Mixed-Print" = PC4)

head(prc_sample_features, 20)
```


```{r}
prc_sample_features %>% 
  select(age, `Cheap-Active-Men`, `Multiple-Items`, Commando, `Front-Mixed-Print`) %>% 
  pivot_longer(cols = -age,names_to = "component",values_to = "loading") %>% 
  ggplot(aes(loading, fill=age))+
  geom_density(alpha=0.5)+
  scale_x_log10()+
  facet_grid(.~component)
```


```{r}
all_sample_trans_features_ml <- all_sample_trans_count %>%
  mutate(t_dat = as.Date(t_dat)) %>%
  mutate(strappy = as.integer(str_detect(words,"[Ss]trappy | strap"))) %>% 
  mutate(cropped = as.integer(str_detect(words,"[Cc]ropped | crop"))) %>%
  mutate(fitted = as.integer(str_detect(words,"[Ff]itted"))) %>%
  mutate(front_print = as.integer(str_detect(words,"[Ff]ront | [Pp]rint"))) %>%
  mutate(mixed_solid_p = as.integer(str_detect(words,"[Mm]ixed | [Ss]olid | [Pp]rint"))) %>%
  mutate(placement_p = as.integer(str_detect(words,"[Pp]lacement | [Pp]rint"))) %>%
  mutate(underwear = as.integer(str_detect(words,"[Uu]nderwear"))) %>%
  mutate(bandeau = as.integer(str_detect(words,"[Bb]andeau"))) %>%
  mutate(men = as.integer(str_detect(words,"[Mm]en"))) %>%
  mutate(dusty = as.integer(str_detect(words,"[Dd]usty"))) %>%
  select(-words, -s_age, -X, -customer_id, -age, -t_dat, -postal_code, -article_id)

head(all_sample_trans_features_ml)
```


```{r}
all_sample_trans_features_ml <- dummy_cols(all_sample_trans_features_ml, select_columns = "club_member_status")

all_sample_trans_features_ml <- all_sample_trans_features_ml %>%
  select(-club_member_status)

head(all_sample_trans_features_ml)
```



```{r}
library(gbm)

sample_index_ml <- createDataPartition(all_sample_trans_features_ml$age_group, p = 0.8, list = FALSE)
sample_tr_ml <- all_sample_trans_features_ml[ sample_index_ml, ]
sample_te_ml <- all_sample_trans_features_ml[-sample_index_ml, ]


ml_ctrl <- trainControl(method = "cv", number=3)

ml_fit <- train(age_group ~ .,
             data = sample_tr_ml, 
             method = "gbm",
             verbose=FALSE,
             trControl = ml_ctrl)

ml_fit
```


```{r}
confusionMatrix(factor(predict(ml_fit, newdata=sample_te_ml)),factor(sample_te_ml$age_group))
```


```{r}
table(sample_tr_ml$age_group)
```


```{r}
(2768856)/(2768856+4828076)
```


```{r}
glm_fit <- train(age_group ~ .,
             data = sample_tr_ml, 
             trControl = ml_ctrl,
             method = "glm",
             family = "binomial")

odds_ratio <- exp(coef(glm_fit$finalModel))
data.frame(name = names(odds_ratio), odds_ratio = odds_ratio) %>%  
  arrange(desc(odds_ratio)) %>% 
  head(10)
```


```{r}
sample_te_ml <- sample_te_ml %>%
  mutate(age_group = ifelse(age_group == "mature", 1, 0))

head(sample_te_ml)
```


```{r}
glm_prob <- predict(glm_fit, newdata=sample_te_ml)
glm_pred <- ifelse(glm_prob > 0.5, 1, 0)

confusionMatrix(glm_pred, sample_te_ml$age_group)
```



