---
title: "510 MSDS Captone Code 2"
author: "Rochelle Rafn"
date: '2022-07-24'
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytext)
library(ggplot2)
library(skimr)
library(devtools)
library(visdat)
library(dplyr)
library(caret)
library(SnowballC)
  data(stop_words)

articles <- read.csv('/Users/rochellerafn/RStudio Files/h-and-m-personalized-fashion-recommendations/articles.csv')
customers <- read.csv('/Users/rochellerafn/RStudio Files/h-and-m-personalized-fashion-recommendations/customers.csv')
transactions <- read.csv('/Users/rochellerafn/RStudio Files/h-and-m-personalized-fashion-recommendations/transactions_train.csv')
```

```{r}
articles <- articles %>%
  mutate(article_id = as.character(article_id)) %>%
  select(-product_code, -product_type_no, -graphical_appearance_no, -colour_group_code, -perceived_colour_master_id, -department_no, -index_code, -index_group_no, -index_group_no, -garment_group_no, -perceived_colour_value_id, -section_no)

str(articles)
```

```{r}
customers <- customers %>%
  mutate(customer_id = as.character(customer_id)) %>%
  filter(!is.na(age), club_member_status == "ACTIVE") %>%
  select(-FN, -fashion_news_frequency)

customers[["Active"]][is.na(customers[["Active"]])] <- 0

str(customers)
```

```{r}
transactions <- transactions %>%
  mutate(article_id = as.character(article_id), customer_id = as.character(customer_id), t_dat = as.Date(t_dat)) %>%
  filter(!is.na(price), !is.na(t_dat))

str(transactions)
```

```{r}
ggplot(customers, aes(age))+
  geom_bar(fill = 'black')+
  theme_bw()+
  xlim(15, 80)
```

```{r}
library(skimr)
skim(customers)
```


```{r}
# Number of total customers in data set
length(unique(customers$customer_id))
```

```{r}
young_customers <- customers %>%
  filter(age <= 39)

str(young_customers)
```

```{r}
ggplot(young_customers, aes(age))+
  geom_bar(fill="black")+
  theme_bw()
```


```{r}
mature_customers <- customers %>%
  filter(age >= 40)

str(mature_customers)
```

```{r}
ggplot(mature_customers, aes(age))+
  geom_bar(fill="black")+
  theme_bw()+
  xlim(39,80)
```

```{r}
summary(young_customers)
```

```{r}
summary(mature_customers)
```


```{r}
young_transactions <- inner_join(x=transactions, y=young_customers, by = 'customer_id')

str(young_transactions)
```



```{r}
mature_transactions <- inner_join(x=transactions, y=mature_customers, by = 'customer_id')

str(mature_transactions)
```

```{r}
# how many *different* items they purchased in a transaction 

young_tcount <- young_transactions %>%
  select(t_dat, customer_id, age, article_id) %>%
  group_by(t_dat, customer_id) %>%
  count(customer_id, sort = TRUE)

head(young_tcount)
```

```{r}
young_tcount <- young_tcount %>%
  mutate(n_items = n) %>%
  select(-n)

head(young_tcount)
```


```{r}
young_transactions <- merge(x=young_transactions, y=young_tcount, by.x= c("t_dat", "customer_id"), by.y = c("t_dat", "customer_id"), all.x = TRUE)

head(young_transactions)
```


```{r}
summary(young_transactions$n_items)
```

```{r}
ggplot(young_transactions, aes(n_items))+
  geom_boxplot()+
  scale_x_log10()
```


```{r}
young_transactions %>%
  filter(t_dat == "2019-02-23", customer_id == "61da44a2758206d5701771f4315637b40c8321b511191654fb1430a6408e4dfa")
```

```{r}
articles %>%
  filter(article_id %in% c("507909001", "501616007"))
```




```{r}
mature_tcount <- mature_transactions %>%
  select(t_dat, customer_id, age, article_id) %>%
  group_by(t_dat, customer_id) %>%
  count(customer_id, sort = TRUE)

head(mature_tcount)
```

```{r}
mature_tcount <- mature_tcount %>%
  mutate(n_items = n) %>%
  select(-n)

head(mature_tcount)
```


```{r}
mature_transactions <- merge(x=mature_transactions, y=mature_tcount, by.x= c("t_dat", "customer_id"), by.y = c("t_dat", "customer_id"), all.x = TRUE)

head(mature_transactions)
```


```{r}
summary(mature_transactions$n_items)
```

```{r}
ggplot(mature_transactions, aes(n_items))+
  geom_boxplot()+
  scale_x_log10()
```

```{r}
young_transactions_n <- young_transactions %>%
  filter(n_items <= 15)

str(young_transactions_n)
```

```{r}
mature_transactions_n <- mature_transactions %>%
  filter(n_items <= 15)

str(mature_transactions_n)
```

```{r}
summary(young_transactions_n$price)
```

```{r}
summary(mature_transactions_n$price)
```

```{r}
only_age <- customers %>%
  select(customer_id, age)

head(only_age)
```

```{r}
all_age_transactions <- inner_join(x=transactions, y=only_age, by="customer_id")

str(all_age_transactions)
```

```{r}
all_age_transactions <- all_age_transactions %>%
  mutate(age_group = ifelse(age < 40, "young", "mature"))
  
str(all_age_transactions)
```

```{r}
all_age_transactions <- all_age_transactions %>%
  mutate(s_age = scale(age, center = TRUE, scale = TRUE))

str(all_age_transactions)
```


```{r}
# plot(s_age ~ price, all_age_transactions)
```

```{r}
age_price_lm <- lm(s_age ~ price, data = all_age_transactions)

summary(age_price_lm)
```

```{r}
young_article_count <- young_transactions %>%
  select(article_id) %>%
  group_by(article_id) %>%
  count() %>%
  arrange(desc(n))

young_article_count <- young_article_count %>%
  mutate(total_items_sold = n) %>%
  select(-n)

head(young_article_count)
```

```{r}
mature_article_count <- mature_transactions %>%
  select(article_id) %>%
  group_by(article_id) %>%
  count() %>%
  arrange(desc(n))

mature_article_count <- mature_article_count %>%
  mutate(total_items_sold = n) %>%
  select(-n)

head(mature_article_count)
```

```{r}
young_unique <- unique(young_article_count$article_id)

head(young_unique)
```

```{r}
mature_unique <- unique(mature_article_count$article_id)

head(mature_unique)
```

```{r}
young_unique_items <- dplyr::setdiff(young_unique,mature_unique)

head(young_unique_items)
```

```{r}
mature_unique_items <- dplyr::setdiff(mature_unique, young_unique)

head(mature_unique_items)
```

```{r}
str(young_unique_items)
```

```{r}
young_article_count %>%
  filter(article_id %in% young_unique_items) %>%
  arrange(desc(total_items_sold))
```

```{r}
mature_article_count %>%
  filter(article_id %in% mature_unique_items) %>%
  arrange(desc(total_items_sold))
```

```{r}
young_articles <- articles %>%
  filter(article_id %in% young_article_count$article_id)

young_articles
```

```{r}
mature_articles <- articles %>%
  filter(article_id %in% mature_article_count$article_id)

mature_articles
```

```{r}
young_article_words <- young_articles %>% 
  rowwise %>% 
  mutate(words = c_across(c(prod_name, product_type_name, product_group_name, graphical_appearance_name, colour_group_name, perceived_colour_value_name, perceived_colour_master_name, department_name, index_name, index_group_name, section_name, garment_group_name, detail_desc)) %>% 
  unique %>% 
  str_c(collapse = " ")) %>% 
  ungroup %>%
  select(-prod_name, -product_type_name, -product_group_name, -graphical_appearance_name, -colour_group_name, -perceived_colour_value_name, -perceived_colour_master_name, -department_name, -index_name, -index_group_name, -section_name, -garment_group_name, -detail_desc)

head(young_article_words)
```

```{r}
young_article_words$words <- gsub("[[:punct:]]", "", young_article_words$words)
young_article_words$words <- gsub('[0-9]+', '', young_article_words$words)
young_article_words[[2]] <- tolower(young_article_words[[2]])

head(young_article_words)
```

```{r}
library(functional)

young_article_words_u <- strsplit(young_article_words$words, " ")

young_article_words_u <- sapply(young_article_words_u, Compose(unique, Curry(paste, collapse=' ')))

head(young_article_words_u)
```

```{r}
young_words_df <- data_frame(Text = young_article_words_u)

head(young_words_df, n = 20)
```

```{r}
young_count_words <- young_words_df %>% 
                  unnest_tokens(output = word, input = Text)
```

```{r}
young_count_words <- young_count_words %>%
  anti_join(stop_words)
```

```{r}
young_wordcounts <- young_count_words %>% 
  count(word, sort = TRUE)

head(young_wordcounts, 20)
```

```{r}
mature_article_words <- mature_articles %>% 
  rowwise %>% 
  mutate(words = c_across(c(prod_name, product_type_name, product_group_name, graphical_appearance_name, colour_group_name, perceived_colour_value_name, perceived_colour_master_name, department_name, index_name, index_group_name, section_name, garment_group_name, detail_desc)) %>% 
  unique %>% 
  str_c(collapse = " ")) %>%
  ungroup %>%
  select(-prod_name, -product_type_name, -product_group_name, -graphical_appearance_name, -colour_group_name, -perceived_colour_value_name, -perceived_colour_master_name, -department_name, -index_name, -index_group_name, -section_name, -garment_group_name, -detail_desc)

head(mature_article_words)
```

```{r}
mature_article_words$words <- gsub("[[:punct:]]", "", mature_article_words$words)
mature_article_words[[2]] <- tolower(mature_article_words[[2]])
mature_article_words$words <- gsub('[0-9]+', '', mature_article_words$words)

head(mature_article_words)
```

```{r}
mature_article_words_u <- strsplit(mature_article_words$words, " ")

mature_article_words_u <- sapply(mature_article_words_u, Compose(unique, Curry(paste, collapse=' ')))
```

```{r}
head(mature_article_words_u)
```

```{r}
mature_words_df <- data_frame(Text = mature_article_words_u)

head(mature_words_df, n = 20)
```

```{r}
mature_count_words <- mature_words_df %>% 
                  unnest_tokens(output = word, input = Text)
```

```{r}
mature_count_words <- mature_count_words %>%
  anti_join(stop_words)
```

```{r}
mature_wordcounts <- mature_count_words %>% 
  count(word, sort = TRUE)

head(mature_wordcounts, 20)
```

```{r}
library(tm)
library(wordcloud)

young_cor_words <- young_article_words[[2]] 
mature_cor_words <- mature_article_words_u[[1]] 
```

```{r}
young_cor_words <- Corpus(VectorSource(young_article_words[[2]]))
mature_cor_words <- Corpus(VectorSource(mature_article_words[[2]]))
```

```{r}
young_cor_words <- tm_map(young_cor_words, removeNumbers)
```

```{r}
mature_cor_words <- tm_map(mature_cor_words, removeNumbers)
```

```{r}
young_cor_words <- tm_map(young_cor_words, removeWords, stopwords('english'))
```

```{r}
mature_cor_words <- tm_map(mature_cor_words, removeWords, stopwords('english'))
```

```{r}
wordcloud(young_cor_words, scale = c(2, 1), min.freq = 10000, colors = rainbow(30))
```

```{r}
wordcloud(mature_cor_words, scale = c(2, 1), min.freq = 10000, colors = rainbow(30))
```

```{r}
young_words_df <- data_frame(Text = young_article_words$words)

head(young_words_df, n = 20)
```

```{r}
young_words_df$Text <- gsub('[0-9]+', '', young_words_df$Text)

head(young_words_df, 10)
```

```{r}
# paste(unique(young_words_df), collapse = ' ')
```


```{r}
young_count_words <- young_words_df %>% 
                  unnest_tokens(output = word, input = Text)

young_count_words
```

```{r}
young_count_words <- young_count_words %>%
  anti_join(stop_words)

young_count_words
```

```{r}
young_wordcounts <- young_count_words %>% 
  count(word, )

head(young_count_words, 20)
```

```{r}
young_u_wordcount <- dplyr::setdiff(young_wordcounts$word, mature_wordcounts$word)

young_u_wordcount
```

```{r}
mature_u_wordcount <- dplyr::setdiff(mature_wordcounts$word, young_wordcounts$word)

mature_u_wordcount
```

```{r}
young_wordcounts %>%
  filter(word %in% young_u_wordcount) %>%
  arrange(desc(n))
```


```{r}
mature_wordcounts %>%
  filter(word %in% mature_u_wordcount) %>%
  arrange(desc(n))
```

```{r}
customer_index <- createDataPartition(customers$age, p = 0.3, list = FALSE)
customer_sample <- customers[ customer_index, ]
customer_remove <- customers[-customer_index, ]

str(customer_sample)
```

```{r}
customer_sample <- customer_sample %>%
  filter(!is.na(age))

str(customer_sample)
```


```{r}
ggplot(customer_sample, aes(age))+
  geom_bar(fill = "black")+
  theme_bw()+
  xlim(16,80)
```

```{r}
all_sample_transactions <- left_join(x=customer_sample, y=all_age_transactions, by=c("customer_id", "age"))

str(all_sample_transactions)
```


```{r}
young_sample <- customer_sample %>%
  filter(age < 40)

str(young_sample)
```

```{r}
mature_sample <- customer_sample %>%
  filter(age >= 40)

str(mature_sample)
```

```{r}
summary(young_sample$age)
```

```{r}
summary(mature_sample$age)
```


```{r}
all_article_words <- articles %>% 
  rowwise %>% 
  mutate(words = c_across(c(prod_name, product_type_name, product_group_name, graphical_appearance_name, colour_group_name, perceived_colour_value_name, perceived_colour_master_name, department_name, index_name, index_group_name, section_name, garment_group_name, detail_desc)) %>% 
  unique() %>% 
  str_c(collapse = " ")) %>% 
  ungroup %>%
  select(-prod_name, -product_type_name, -product_group_name, -graphical_appearance_name, -colour_group_name, -perceived_colour_value_name, -perceived_colour_master_name, -department_name, -index_name, -index_group_name, -section_name, -garment_group_name, -detail_desc)

head(all_article_words)
```

```{r}
all_article_words$words <- gsub("[[:punct:]]", "", all_article_words$words)
all_article_words[[2]] <- tolower(all_article_words[[2]])
all_article_words$words <- gsub('[0-9]+', '', all_article_words$words)

head(all_article_words)
```

```{r}
all_sample_transactions <- left_join(x=all_sample_transactions, y=all_article_words, by="article_id")

str(all_sample_transactions)
```

```{r}
# write.csv(all_sample_transactions, '/Users/rochellerafn/RStudio Files/h-and-m-personalized-fashion-recommendations/all_sample_transactions')
```


```{r}
young_sample_trans <- all_sample_transactions %>%
  filter(age < 40)

str(young_sample_trans)
```

```{r}
young_sample_words_u <- strsplit(young_sample_trans$words, " ")

young_sample_words_u <- sapply(young_sample_words_u, Compose(unique, Curry(paste, collapse=' ')))
```


```{r}
young_sample_words_df <- data_frame(Text = young_sample_words_u)

head(young_sample_words_df, n = 20)
```

```{r}
young_sample_count_words <- young_sample_words_df %>% 
                  unnest_tokens(output = word, input = Text)
```

```{r}
young_sample_count_words <- young_sample_count_words %>%
  anti_join(stop_words)
```

```{r}
young_sample_wordcounts <- young_sample_count_words %>% 
  count(word, sort = TRUE)

head(young_sample_wordcounts, 20)
```

```{r}
# young_sample_cor <- Corpus(VectorSource(young_sample_count_words$Text))
```

```{r}
# wordcloud(young_sample_cor, scale = c(2, 1), min.freq = 800000, colors = rainbow(30))
```

```{r}
mature_sample_trans <- all_sample_transactions %>%
  filter(age >= 40)

str(mature_sample_trans)
```

```{r}
mature_sample_words_u <- strsplit(mature_sample_trans$words, " ")

mature_sample_words_u <- sapply(mature_sample_words_u, Compose(unique, Curry(paste, collapse=' ')))
```

```{r}
mature_sample_words_df <- data_frame(Text = mature_sample_trans$words)

head(mature_sample_words_df, n = 20)
```

```{r}
mature_sample_count_words <- mature_sample_words_df %>% 
                  unnest_tokens(output = word, input = Text)
```

```{r}
mature_sample_count_words <- mature_sample_count_words %>%
  anti_join(stop_words)

head(mature_sample_count_words)
```

```{r}
mature_sample_wordcounts <- mature_sample_count_words %>% 
  count(word, sort = TRUE)

head(mature_sample_wordcounts)
```

```{r}
mature_sample_uwords <- dplyr::setdiff(mature_sample_count_words, young_sample_count_words)

mature_sample_uwords <- mature_sample_uwords %>%
  filter(!is.na(word))

head(mature_sample_uwords, 20)
```

```{r}
young_sample_uwords <- dplyr::setdiff(young_sample_count_words, mature_sample_count_words)

young_sample_uwords <- young_sample_uwords %>%
  filter(!is.na(word))

head(young_sample_uwords, 20)
```

```{r}
mature_sample_wordcounts %>%
  filter(word %in% mature_sample_uwords)
```


```{r}
# young_sample_cor <- Corpus(VectorSource(young_sample_words_df))
```

```{r}
# mature_sample_cor <- Corpus(VectorSource(mature_sample_words_df))
```

```{r}
# young_sample_cor <- tm_map(young_sample_cor, removeWords, stopwords('english'))
```

```{r}
# mature_sample_cor <- tm_map(mature_sample_cor, removeWords, stopwords('english'))
```

```{r}
# wordcloud(young_sample_cor, scale = c(2, 1), min.freq = 800000, colors = rainbow(30))
```

```{r}
# wordcloud(mature_sample_cor, scale = c(2, 1), min.freq = 800000, colors = rainbow(30))
```

```{r}
graphic_appearance <- articles %>%
  select(article_id, graphical_appearance_name)

head(graphic_appearance)
```

```{r}
all_sample_transactions <- left_join(x=all_sample_transactions, y=graphic_appearance, by="article_id")

str(all_sample_transactions)
```

```{r}
all_sample_transactions %>%
  group_by(age_group) %>%
  count(graphical_appearance_name) %>%
  arrange(desc(n))
```

```{r}
library(moderndive)
graphic_lm <- lm(age ~ graphical_appearance_name, data = all_sample_transactions)

get_regression_table(graphic_lm)
get_regression_summaries(graphic_lm)
```

```{r}
all_sample_transactions %>%
  filter(!is.na(graphical_appearance_name)) %>%
ggplot() +
  aes(
    x = graphical_appearance_name,
    fill = graphical_appearance_name
  ) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  scale_y_log10()+
  theme_minimal() +
  scale_x_discrete(guide = guide_axis(angle = 90))+
  facet_wrap(vars(age_group))
```


